version: "3.8"

services:
  backend:
    image: nikkaman07/discover-dollar-backend:latest
    container_name: discover-deploy-backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongo

  frontend:
    image: nikkaman07/discover-dollar-frontend:latest
    container_name: discover-deploy-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: discover-deploy-mongo
    ports:
      - "27017:27017"
    volumes:
      - discover-deploy_mongo-data:/data/db
    restart: always

volumes:
  discover-deploy_mongo-data:

